import {
  mdiEmoticonAngryOutline,
  mdiEmoticonAngry,
  mdiEmoticonConfused,
  mdiEmoticonConfusedOutline,
  mdiEmoticonCoolOutline,
  mdiEmoticonCool,
  mdiEmoticonCryOutline,
  mdiEmoticonCry,
  mdiEmoticonDeadOutline,
  mdiEmoticonDead,
  mdiEmoticonDevilOutline,
  mdiEmoticonDevil,
  mdiEmoticonExcitedOutline,
  mdiEmoticonExcited,
  mdiEmoticonFrown,
  mdiEmoticonFrownOutline,
  mdiEmoticonHappyOutline,
  mdiEmoticonHappy,
  mdiEmoticonKissOutline,
  mdiEmoticonKiss,
  mdiEmoticonLol,
  mdiEmoticonLolOutline,
  mdiEmoticonMinus,
  mdiEmoticonMinusOutline,
  mdiEmoticonNeutralOutline,
  mdiEmoticonNeutral,
  mdiEmoticonOutline,
  mdiEmoticonPlus,
  mdiEmoticonPlusOutline,
  mdiEmoticonPoopOutline,
  mdiEmoticonPoop,
  mdiEmoticonRemove,
  mdiEmoticonRemoveOutline,
  mdiEmoticonSadOutline,
  mdiEmoticonSad,
  mdiEmoticonSick,
  mdiEmoticonSickOutline,
  mdiEmoticon,
  mdiEmoticonTongueOutline,
  mdiEmoticonTongue,
  mdiEmoticonWinkOutline,
  mdiEmoticonWink,
} from "@mdi/js";

export const emoticonOptions = [
  {
    label: "Angry Outline",
    value: "emoticon-angry-outline",
    icon: mdiEmoticonAngryOutline,
  },
  { label: "Angry", value: "emoticon-angry", icon: mdiEmoticonAngry },
  { label: "Confused", value: "emoticon-confused", icon: mdiEmoticonConfused },
  {
    label: "Confused Outline",
    value: "emoticon-confused-outline",
    icon: mdiEmoticonConfusedOutline,
  },
  {
    label: "Cool Outline",
    value: "emoticon-cool-outline",
    icon: mdiEmoticonCoolOutline,
  },
  { label: "Cool", value: "emoticon-cool", icon: mdiEmoticonCool },
  {
    label: "Cry Outline",
    value: "emoticon-cry-outline",
    icon: mdiEmoticonCryOutline,
  },
  { label: "Cry", value: "emoticon-cry", icon: mdiEmoticonCry },
  {
    label: "Dead Outline",
    value: "emoticon-dead-outline",
    icon: mdiEmoticonDeadOutline,
  },
  { label: "Dead", value: "emoticon-dead", icon: mdiEmoticonDead },
  {
    label: "Devil Outline",
    value: "emoticon-devil-outline",
    icon: mdiEmoticonDevilOutline,
  },
  { label: "Devil", value: "emoticon-devil", icon: mdiEmoticonDevil },
  {
    label: "Excited Outline",
    value: "emoticon-excited-outline",
    icon: mdiEmoticonExcitedOutline,
  },
  { label: "Excited", value: "emoticon-excited", icon: mdiEmoticonExcited },
  { label: "Frown", value: "emoticon-frown", icon: mdiEmoticonFrown },
  {
    label: "Frown Outline",
    value: "emoticon-frown-outline",
    icon: mdiEmoticonFrownOutline,
  },
  {
    label: "Happy Outline",
    value: "emoticon-happy-outline",
    icon: mdiEmoticonHappyOutline,
  },
  { label: "Happy", value: "emoticon-happy", icon: mdiEmoticonHappy },
  {
    label: "Kiss Outline",
    value: "emoticon-kiss-outline",
    icon: mdiEmoticonKissOutline,
  },
  { label: "Kiss", value: "emoticon-kiss", icon: mdiEmoticonKiss },
  { label: "LOL", value: "emoticon-lol", icon: mdiEmoticonLol },
  {
    label: "LOL Outline",
    value: "emoticon-lol-outline",
    icon: mdiEmoticonLolOutline,
  },
  { label: "Minus", value: "emoticon-minus", icon: mdiEmoticonMinus },
  {
    label: "Minus Outline",
    value: "emoticon-minus-outline",
    icon: mdiEmoticonMinusOutline,
  },
  {
    label: "Neutral Outline",
    value: "emoticon-neutral-outline",
    icon: mdiEmoticonNeutralOutline,
  },
  { label: "Neutral", value: "emoticon-neutral", icon: mdiEmoticonNeutral },
  { label: "Outline", value: "emoticon-outline", icon: mdiEmoticonOutline },
  { label: "Plus", value: "emoticon-plus", icon: mdiEmoticonPlus },
  {
    label: "Plus Outline",
    value: "emoticon-plus-outline",
    icon: mdiEmoticonPlusOutline,
  },
  {
    label: "Poop Outline",
    value: "emoticon-poop-outline",
    icon: mdiEmoticonPoopOutline,
  },
  { label: "Poop", value: "emoticon-poop", icon: mdiEmoticonPoop },
  { label: "Remove", value: "emoticon-remove", icon: mdiEmoticonRemove },
  {
    label: "Remove Outline",
    value: "emoticon-remove-outline",
    icon: mdiEmoticonRemoveOutline,
  },
  {
    label: "Sad Outline",
    value: "emoticon-sad-outline",
    icon: mdiEmoticonSadOutline,
  },
  { label: "Sad", value: "emoticon-sad", icon: mdiEmoticonSad },
  { label: "Sick", value: "emoticon-sick", icon: mdiEmoticonSick },
  {
    label: "Sick Outline",
    value: "emoticon-sick-outline",
    icon: mdiEmoticonSickOutline,
  },
  { label: "Default", value: "emoticon", icon: mdiEmoticon },
  {
    label: "Tongue Outline",
    value: "emoticon-tongue-outline",
    icon: mdiEmoticonTongueOutline,
  },
  { label: "Tongue", value: "emoticon-tongue", icon: mdiEmoticonTongue },
  {
    label: "Wink Outline",
    value: "emoticon-wink-outline",
    icon: mdiEmoticonWinkOutline,
  },
  { label: "Wink", value: "emoticon-wink", icon: mdiEmoticonWink },
];
